# Generated by Django 4.1 on 2023-07-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeBanking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Debit', 'Debit'), ('Transfer', 'Transfer'), ('Deposit', 'Deposit')], max_length=30),
        ),
    ]
