# Generated by Django 4.1 on 2023-07-30 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeBanking', '0005_remove_transaction_recipient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.AddField(
            model_name='transaction',
            name='account_recipient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='recipent_account', to='homeBanking.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account_sender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sender_account', to='homeBanking.account'),
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
