# Generated by Django 4.1 on 2023-08-02 18:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homeBanking', '0006_remove_transaction_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='card_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
