# Generated by Django 4.1 on 2023-08-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeBanking', '0008_alter_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.CharField(choices=[('Aurora_Finance_Bank', 'Aurora_Finance_Bank'), ('NexaBank', 'NexaBank'), ('Horizon_Trust_Bank', 'Horizon_Trust_Bank'), ('Crescent_Financial_Bank', 'Crescent_Financial_Bank'), ('Veridian_Bank', 'Veridian_Bank'), ('Pinnacle_Finance_Bank', 'Pinnacle_Finance_Bank'), ('Solstice_Savings_Bank', 'Solstice_Savings_Bank'), ('Equinox_Capital_Bank', 'Equinox_Capital_Bank'), ('Voyager_Bancorp_Bank', 'Voyager_Bancorp_Bank')], default='', max_length=100),
        ),
    ]
