# Generated by Django 4.1 on 2023-09-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeBanking', '0011_rename_service_service_service_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service_amount',
            new_name='amount_service',
        ),
        migrations.AddField(
            model_name='service',
            name='service_account',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='service',
            name='expiration_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='service',
            name='paid_date',
            field=models.DateField(default=None),
        ),
        migrations.RemoveField(
            model_name='user',
            name='service',
        ),
        migrations.AddField(
            model_name='user',
            name='service',
            field=models.ManyToManyField(blank=True, related_name='service', to='homeBanking.service'),
        ),
    ]
