# Generated by Django 4.1 on 2023-09-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeBanking', '0013_alter_service_amount_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='amount_service',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='expiration_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='service',
            name='paid_date',
            field=models.DateField(blank=True, default=None),
        ),
    ]
