# Generated by Django 4.1 on 2023-09-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeBanking', '0014_alter_service_amount_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='paid_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
