# Generated by Django 4.1 on 2023-09-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeBanking', '0018_alter_service_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='expiration_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='service',
            name='paid_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
