# Generated by Django 4.1 on 2023-09-09 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeBanking', '0019_alter_service_expiration_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='service',
        ),
        migrations.AddField(
            model_name='service',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='service', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='service_account', to='homeBanking.account'),
        ),
    ]
