# Generated by Django 4.1 on 2023-09-10 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeBanking', '0020_remove_user_service_service_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_transaction', to='homeBanking.transaction'),
        ),
    ]
