# Generated by Django 4.1 on 2023-09-10 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeBanking', '0021_service_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='transaction',
            new_name='service_transaction',
        ),
    ]
