# Generated by Django 4.1 on 2023-10-02 21:42

from django.db import migrations, models
import homeBanking.models


class Migration(migrations.Migration):

    dependencies = [
        ('homeBanking', '0022_rename_transaction_service_service_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.IntegerField(default=0, unique=True, validators=[homeBanking.models.validate_dni]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
