# Generated by Django 4.1 on 2023-10-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeBanking', '0023_alter_user_dni_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(choices=[('Credit', 'Credit')], max_length=100),
        ),
    ]
