# Generated by Django 4.1 on 2023-10-07 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeBanking', '0025_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
